'''
DICIONARIOS - 
DADOS = {'NOME':'PEDRO','IDADE':'25'}
PRINT(DADOS['NOME']) ---- PEDRO
PRINT(DADOS['IDADE']) ---- 25

INCLUIR ELEMENTOS - NÃO PRECISA APENND SOMENTE CRIAR O ELEMENTO 
DADOS['SEXO'] = 'M'

REMOVER ELEMENTOS 
DELDADOS['IDADE'] - PERDE ELEMENTO E VALOR 

FILME {
    'TITULO':'STAR WARS',
    'ANO':'1977',
    'DIRETOR':'GEORGE LUCAS'
      }
PRINT(FILME.VALUES()) ---- STAR WARS 1977 GEORGE LUCAS
PRINT(FILME.KEYS()) ------ TITULO     ANO  DIRETOR 
PRINT(FILME.ITEM()) ------ TODOS SO VALORES DE FILME

FOR K, V IN FILME.ITEM():
PRINT(F' O {K} É {V}')

O TITULO É STARS WARS 
O ANO E 1977
O DIRETRO É GEORGE LUCAS 

-----------------------------------------------------------

'''